title: Darrell DeMakes Portfolio
description: My DAE 6 Month Journey
show_downloads: true
google_analytics:
theme: jekyll-theme-cayman
baseurl: /DD-6-Month-DAE

nav:
  - name: Home
    url: /
  - name: Projects
    url: /projects/
  - name: Resume
    url: /resume/
  - name: About Me
    url: /about/
  - name: Contact
    url: /contact/
