title: Darrell DeMakes Portfolio
description: My DAE 6 Month Journey
show_downloads: true
google_analytics:
remote_theme: pages-themes/tactile@v0.2.0
baseurl: /DD-6-Month-DAE
plugins:
  - jekyll-remote-theme

collections:
  pages:
    output: true
    permalink: /:name/

defaults:
  - scope:
      path: ""
    values:
      layout: "default"
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"

# Navigation links
nav:
  - name: Home
    url: /
  - name: About
    url: /about/
  - name: Resume
    url: /resume/
  - name: Projects
    url: /projects/
  - name: Contact
    url: /contact/
